expr_name: ${hydra:job.config_name}

mode: train
total_steps: 10000
resume_ckpt: null
print_every: 100
save_every: 1000
valid_every: 1000
ckpt_dir: ./expr
test_ckpt: last
device_id: 0

data:
  train_paths: ["/media/toonnyy8/DC462D80462D5C90/datatank/dataset/Imagenet/Imagenet32/train/train_data_batch_1",
                "/media/toonnyy8/DC462D80462D5C90/datatank/dataset/Imagenet/Imagenet32/train/train_data_batch_2"]
  valid_paths: ["/media/toonnyy8/DC462D80462D5C90/datatank/dataset/Imagenet/Imagenet32/train/train_data_batch_3",]
  test_paths: ["/media/toonnyy8/DC462D80462D5C90/datatank/dataset/Imagenet/Imagenet32/valid/val_data"]

  train_batch_size: 1024
  valid_batch_size: 1024
  test_batch_size: 1024

  num_workers: 8

  augment: False

optim:
  optim_type: Adam
  optim_args:
    lr: 1e-3
  regul_lambda: 0.0002
  regul_ord: null
